// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfcZc4bQT2f5sBp__p20MBqRIuTxdt3xQ',
    appId: '1:591427131231:android:99b0b0176f8cbb837c08ea',
    messagingSenderId: '591427131231',
    projectId: 'calculator-bf2ea',
    storageBucket: 'calculator-bf2ea.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdjXP-2QrLjdUADg9ZZAgkons0VR8k--Q',
    appId: '1:591427131231:ios:a8d62d4875b5b0277c08ea',
    messagingSenderId: '591427131231',
    projectId: 'calculator-bf2ea',
    storageBucket: 'calculator-bf2ea.appspot.com',
    androidClientId: '591427131231-5qslrhbkm4er464jvvldk2rj1o85skb2.apps.googleusercontent.com',
    iosClientId: '591427131231-dhuj0bnsq1a6u4dgm38f58g9epvdg1c3.apps.googleusercontent.com',
    iosBundleId: 'com.example.calculator',
  );
}
